### ISSUE TITLE
Missing packages?

### ISSUE THREAD

**Issue by saifulmuhajir** [cz-guardian/fedora-deepin#2]
Followed the steps but while trying to install the packages, it seems that some are missing:
```
No package dde-control-center available.
No package dde-dock available.
No package dde-launcher available.
No package dde-session-ui available.
```

Using tab as autocomplete for `dde-` is not picking up anything.

OS: Fedora 25 x64
Kernel: Linux 4.10

**Comment by cz-guardian** [comment]
Hi Saiful,

I've fixed the documentation to reflect the latest state. The installation procedure in README is now fixed. Basically all the dde- prefixes were replaced by deepin-, but I recommend that you go through the instructions once more time to make sure everything is fine :).

Have a nice day.
Jaroslav

**Comment by saifulmuhajir** [comment]
Okay, thanks.
